#!/bin/bash

# Proxmox UPS Shutdown
# Copyright © 2023 Mateusz Dera

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


# Shut down containers
for container in `pct list | awk '{print $1}' | sed '1d'`
do
  echo "Shutting down container $container..."
  pct shutdown $container
done

# Shut down virtual machines
for vmid in `qm list | awk '{print $1}' | sed '1d'`
do
  echo "Shutting down virtual machine $vmid..."
  qm shutdown $vmid
done

# Wait for all containers and virtual machines to shut down
echo "Waiting for all containers and virtual machines to shut down..."
while [ $(pct list | grep running | wc -l) -ne 0 ] || [ $(qm list | grep running | wc -l) -ne 0 ]
do
  sleep 10
done

echo "All containers and virtual machines have been shut down."