#!/bin/bash

# Proxmox UPS Shutdown
# Copyright © 2023 Mateusz Dera

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

your_ups=ups@localhost
battery_percentage=85
refresh=10

while true
do
  battery_level=$(upsc $your_ups battery.charge)
  if [ "$battery_level" -lt $battery_percentage ]
    then
      echo "Checking..."
      sleep $refresh
      battery_level_2=$(upsc $your_ups battery.charge)
      if [ "$battery_percentage_2" -lt $battery_percentage ]
        proxmox-shutdown
        break
      fi
    else
      echo $battery_level
      echo "Reloading..."
      sleep $refresh
    fi
done

shutdown -t -s 0